In [1]:
import torch
import numpy as np

In [3]:
# convert numpy to tensor or vise versa

np_data = np.arange(6).reshape(2,3)
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()

print(
    'numpy array:\n', np_data,
    '\ntorch tensor:\n', torch_data,
    '\ntensor to array:\n', tensor2array)

numpy array:
 [[0 1 2]
 [3 4 5]] 
torch tensor:
 tensor([[0, 1, 2],
        [3, 4, 5]]) 
tensor to array:
 [[0 1 2]
 [3 4 5]]


In [5]:
# abs:绝对值
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print(
    'tensor:\n', tensor,
    '\nnumpy:\n', np.abs(data),
    '\ntorch:\n', torch.abs(tensor))

tensor:
 tensor([-1., -2.,  1.,  2.]) 
numpy:
 [1 2 1 2] 
torch:
 tensor([1., 2., 1., 2.])


In [6]:
tensor.abs()

tensor([1., 2., 1., 2.])

In [8]:
# sin
print(
    'sin',
    '\nnumpy: \n', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: \n', torch.sin(tensor)  # [-0.8415 -0.9093  0.8415  0.9093]
)

sin 
numpy: 
 [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch: 
 tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [9]:
print('tensor:\n', tensor)

# sigmoid
print('\nsigmoid:\n', tensor.sigmoid())
# exp
print('\nexp:\n', tensor.exp())

tensor:
 tensor([-1., -2.,  1.,  2.])

sigmoid:
 tensor([0.2689, 0.1192, 0.7311, 0.8808])

exp:
 tensor([0.3679, 0.1353, 2.7183, 7.3891])


In [11]:
# mean
print(
    'mean',
    '\nnumpy: \n', np.mean(data),         # 0.0
    '\ntorch: \n', torch.mean(tensor)     # 0.0
)

mean 
numpy: 
 0.0 
torch: 
 tensor(0.)


In [12]:
# matrix multiplication
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 32-bit floating point
# correct method
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)


matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])


In [14]:
data = np.array([[1,2], [3,4]])
tensor = torch.from_numpy(data)
torch.mm(tensor, tensor)

tensor([[ 7, 10],
        [15, 22]])

In [16]:
print(type(tensor))
tensor.mm(tensor)

<class 'torch.Tensor'>


tensor([[ 7, 10],
        [15, 22]])

In [17]:
tensor * tensor

tensor([[ 1,  4],
        [ 9, 16]])