In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor, requires_grad=True)    # build a variable, usually for compute gradients

print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [5]:
print(variable.grad)

None


In [6]:
# The variable is a part of the auto-gradient

t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [7]:
v_out.backward()

In [8]:
variable.grad

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [9]:
variable

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [10]:
variable.data

tensor([[1., 2.],
        [3., 4.]])

In [11]:
variable.data.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [12]:
v_out = torch.mean(variable*variable)
print("v_out: ", v_out)
v_out.backward()
print("variable.grad: ", variable.grad)

v_out:  tensor(7.5000, grad_fn=<MeanBackward0>)
variable.grad:  tensor([[1., 2.],
        [3., 4.]])


In [13]:
v_out = torch.mean(variable*variable)
print("v_out: ", v_out)
v_out.backward()
print("variable.grad: ", variable.grad)

v_out:  tensor(7.5000, grad_fn=<MeanBackward0>)
variable.grad:  tensor([[1.5000, 3.0000],
        [4.5000, 6.0000]])
